trigger:
  - master  # Déclenchement du pipeline sur la branche 'master'

pool: "default"  # Utilisation du pool d'agents par défaut

variables:
  - name: CloudInitContent  # Variable pour stocker le contenu encodé de Cloud-Init

steps:
  # Étape 1 : Encodage du fichier Cloud-Init en Base64 pour une utilisation ultérieure
  - task: PowerShell@2
    name: Encodage_CloudInit
    inputs:
      targetType: 'inline'
      script: |
        $CloudContent = Get-Content -Path .\VM_Scale_Set_TP1\Cloud-Init.txt -Raw
        Write-Host "Contenu de Cloud-Init :"
        Write-Host $CloudContent
        $encodedContent = [Convert]::ToBase64String([Text.Encoding]::UTF8.GetBytes($CloudContent))
        Write-Host "##vso[task.setvariable variable=CloudInitContent]$encodedContent"

  # Étape 2 : Déploiement du Key Vault et ajout de secrets pour sécuriser les informations sensibles
  - task: AzureResourceManagerTemplateDeployment@3
    name: Creation_KeyVault
    inputs:
      deploymentScope: 'Resource Group'
      azureResourceManagerConnection: 'GroupeDeTP-Service'
      subscriptionId: '41734dbc-edac-4915-a1d9-63da50959410'
      action: 'Create Or Update Resource Group'
      resourceGroupName: 'KeyVaultRG'
      location: 'Canada East'
      templateLocation: 'Linked artifact'
      csmFile: '$(Build.SourcesDirectory)\VM_Scale_Set_TP1\KeyVault\azuredeploy.json'
      csmParametersFile: '$(Build.SourcesDirectory)\VM_Scale_Set_TP1\KeyVault\azuredeploy.parameters.json'
      overrideParameters: '-Secret Vmpassword2024$'
      deploymentMode: 'Incremental'

  # Étape 3 : Récupération du secret AdminPass depuis le Key Vault pour une utilisation dans le déploiement
  - task: AzureKeyVault@2
    name: Recuperation_KeyVault
    inputs:
      azureSubscription: 'GroupeDeTP-Service'
      KeyVaultName: 'KeyvaultPrincTP1'
      SecretsFilter: 'AdminPass'
      RunAsPreJob: false

  # Étape 4 : Déploiement du Virtual Machine Scale Set (VMSS) en utilisant les paramètres de configuration et les données encodées de Cloud-Init
  - task: AzureResourceManagerTemplateDeployment@3
    name: Creation_VMSS
    inputs:
      deploymentScope: 'Resource Group'
      azureResourceManagerConnection: 'GroupeDeTP-Service'
      subscriptionId: '41734dbc-edac-4915-a1d9-63da50959410'
      action: 'Create Or Update Resource Group'
      resourceGroupName: 'GroupeDeTP'
      location: 'Canada East'
      templateLocation: 'Linked artifact'
      csmFile: '$(Build.SourcesDirectory)\VM_Scale_Set_TP1\azuredeploy.json'
      csmParametersFile: '$(Build.SourcesDirectory)\VM_Scale_Set_TP1\azuredeploy.parameters.json'
      overrideParameters: '-customData $(CloudInitContent) -adminPassword $(AdminPass)'
      deploymentMode: 'Incremental'
