trigger:
- master

pool: "default"

variables:
- name: CloudInitContent

steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      $CloudContent = Get-Content -Path .\VM_Scale_Set_TP1\Cloud-Init.txt -Raw
      Write-Host $CloudContent
      $encodedContent = [Convert]::ToBase64String([Text.Encoding]::UTF8.GetBytes($CloudContent))

- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'GroupeDeTP-Service'
    subscriptionId: '41734dbc-edac-4915-a1d9-63da50959410'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'KeyVaultRG'
    location: 'Canada East'
    templateLocation: 'Linked artifact'
    csmFile: '$(Build.SourcesDirectory)\VM_Scale_Set_TP1\KeyVault\azuredeploy.json'
    csmParametersFile: '$(Build.SourcesDirectory)\VM_Scale_Set_TP1\KeyVault\azuredeploy.parameters.json'
    overrideParameters: '-Secret Vmpassword2024$'
    deploymentMode: 'Incremental'

- task: AzureKeyVault@2
  inputs:
    azureSubscription: 'GroupeDeTP-Service'
    KeyVaultName: 'Keyvault_Principale_TP1'
    SecretsFilter: 'AdminPass'
    RunAsPreJob: false

- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'GroupeDeTP-Service'
    subscriptionId: '41734dbc-edac-4915-a1d9-63da50959410'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'GroupeDeTP'
    location: 'Canada East'
    templateLocation: 'Linked artifact'
    csmFile: '$(Build.SourcesDirectory)\VM_Scale_Set_TP1\azuredeploy.json'
    csmParametersFile: '$(Build.SourcesDirectory)\VM_Scale_Set_TP1\azuredeploy.parameters.json'
    overrideParameters: '-customData $(CloudInitContent) -adminPassword $(AdminPass)'
    deploymentMode: 'Incremental'