trigger:
  - master # Déclenche le pipeline uniquement sur la branche master

pool: "default" # Spécifie le pool d'agents pour l'exécution des tâches

variables:
  - name: CloudInitContent

steps:
# Étape d'encodage du fichier Cloud-Init en base64
  - task: PowerShell@2
    name: Encodage_CloudInit
    inputs:
      targetType: 'inline'
      script: |
        $CloudContent = Get-Content -Path .\VM_Scale_Set_TP1\Cloud-Init.txt -Raw
        Write-Host "Contenu de Cloud-Init :"
        Write-Host $CloudContent
        $encodedContent = [Convert]::ToBase64String([Text.Encoding]::UTF8.GetBytes($CloudContent))
        Write-Host "##vso[task.setvariable variable=CloudInitContent]$encodedContent"

   # Déploiement du Key Vault et ajout des secrets nécessaires
  - task: AzureResourceManagerTemplateDeployment@3
    name: Creation_KeyVault
    inputs:
      deploymentScope: 'Resource Group'
      azureResourceManagerConnection: 'GroupeDeTP-Service'
      subscriptionId: '41734dbc-edac-4915-a1d9-63da50959410'
      action: 'Create Or Update Resource Group'
      resourceGroupName: 'KeyVaultRG'
      location: 'Canada East'
      templateLocation: 'Linked artifact'
      csmFile: '$(Build.SourcesDirectory)\VM_Scale_Set_TP1\KeyVault\azuredeploy.json'
      csmParametersFile: '$(Build.SourcesDirectory)\VM_Scale_Set_TP1\KeyVault\azuredeploy.parameters.json'
      overrideParameters: '-Secret Vmpassword2024$'
      deploymentMode: 'Incremental'

  # Récupérer le secret AdminPass depuis Key Vault
  - task: AzureKeyVault@2
    name: Recuperation_KeyVault
    inputs:
      azureSubscription: 'GroupeDeTP-Service'
      KeyVaultName: 'KeyvaultPrincTP1'
      SecretsFilter: 'AdminPass'
      RunAsPreJob: false

  # Déploiement du Scale Set
  - task: AzureResourceManagerTemplateDeployment@3
    name: Creation_VMSS
    inputs:
      deploymentScope: 'Resource Group'
      azureResourceManagerConnection: 'GroupeDeTP-Service'
      subscriptionId: '41734dbc-edac-4915-a1d9-63da50959410'
      action: 'Create Or Update Resource Group'
      resourceGroupName: 'GroupeDeTP'
      location: 'Canada East'
      templateLocation: 'Linked artifact'
      csmFile: '$(Build.SourcesDirectory)\VM_Scale_Set_TP1\azuredeploy.json'
      csmParametersFile: '$(Build.SourcesDirectory)\VM_Scale_Set_TP1\azuredeploy.parameters.json'
      # Récupération du secret AdminPass stocké dans le Key Vault
      overrideParameters: '-customData $(CloudInitContent) -adminPassword $(AdminPass)'
      deploymentMode: 'Incremental'